# this pvc will be used to store downloaded init.sql file
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: init-script
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 50Mi
---
# this pvc will be used to store mysql database
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1 
kind: Deployment
metadata:
  name: mysql-init-demo
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      initContainers:  # this init container download init.sql file using "curl -o <downloaded file name with path> <download url>" command.
      - name: init-script-downloader
        image: docker.io/omegazyadav/mysql:latest
        #     args:
        #       - "-o"
        #       - "/tmp/data/dump.sql" # we are saving downloaded file as init.sql in /tmp/data directory
        #       - "--header 'PRIVATE-TOKEN: 3pvhZA-x977eyRnYhzz9' https://gitlab.com/api/v4/projects/15535774/repository/files/src%2Fdump%2Esql/raw?ref=dockerize " # download url
        volumeMounts:
        - name: init-script # mount the volume where downloaded file will be saved
          mountPath: /tmp/data
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: eydean
        - name: MYSQL_USER
          value: eydean_user
        - name: MYSQL_PASSWORD
          value: eydean_pass
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: data
          mountPath: /var/lib/mysql
        - name: init-script
          mountPath: /docker-entrypoint-initdb.d # we are mounting init-script volume in this directory. so init.sql file will be available here.
      volumes:
      - name: init-script # this volume holds downloaded init.sql file.
        persistentVolumeClaim:
          claimName: init-script
      - name: data # this volume will be used for database storage.
        persistentVolumeClaim:
          claimName: mysql-data-pvc
